[package]
name = "yew-rayon-demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
yew = { path = "../../packages/yew" }
yew-agent = { path = "../../packages/yew-agent" }
gloo-timers = "0.2"
js-sys = "0.3"
log = "0.4"
once_cell = "1.8"
rayon = "1.5"
serde = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-rayon = { version = "1.0", features = ["no-bundler"] }
wasm-logger = "0.2"
